In [107]:
# Learning numpy for the final time hopefully :) Date of Learning 3rd December 2025.
import numpy as np

In [4]:
# Creation of a 1D array.
arr = np.array([1,3,4],dtype = np.int8) # The sytax for creating an array is pretty simple, it is np.array(<listname>,dtype = <datatype>(the default datatype is float64))

In [8]:
# To check for the shape,size of an array.
print(arr.shape) # rows x columns in an array.
print(arr.size) # Number of elements in the array.
print(arr.dtype) # Datatype of the elements in the array.
arr.astype(np.int8) # To change the datatype of the array elements.

(3,)
3
int8


array([1, 3, 4], dtype=int8)

In [11]:
# The datatypes in for an numpy array can be the following...
'''
1)Float: np.float16, np.float32, np.float64
2)Integer: np.int8, np.int16, np.int32, np.int64
3)Boolean: np.bool
4)Complex: np.complex64, np.complex128
5)String: np.str_ (This is useless as numpy arrays are meant for numerical computations.)
The first 3 datatypes are the most commonly used ones. but float8 doesn't exist.
'''

"\n1)Float: np.float16, np.float32, np.float64\n2)Integer: np.int8, np.int16, np.int32, np.int64\n3)Boolean: np.bool\n4)Complex: np.complex64, np.complex128\n5)String: np.str_ (This is useless as numpy arrays are meant for numerical computations.)\nThe first 3 datatypes are the most commonly used ones. but float8 doesn't exist.\n"

In [13]:
# Inedexing and slicing in numpy arrays is similar to that of lists in python.
## Example:
print(arr[0]) # First element
print(arr[0:2]) # First two elements


1
[1 3]


In [16]:
# MultiIndexing is also possible in numpy arrays.
example = np.array([1,2,3,4,45,5,6,7,8,9,0],dtype = np.float16)
print(example[[1,2,3,4]]) # This will print the elements at index 1,2,3 and 4.
# This is so useful because instead of doing this....
## print(example[1],example[2],example[3],example[4])  we can index it just in One line.

[ 2.  3.  4. 45.]


In [18]:
# I am pretty sure the numpy arrays are mutable.
# So...
example[0] = 100
print(example[0]) # YES IT WORKS!

100.0


In [22]:
newarray = example.copy() # To create a copy of an numpy array.
# This is Deep copy.
newarray[1] = 200
print(example[1]) # This will print 2 proving that it is a deep copy.
print(newarray[1]) # This will print 200 proving that it is a deep copy
# Done.

2.0
200.0


In [26]:
# Another important attribute of numpy arrays is ndim.
print(example.ndim) # This will print the number of dimensions of the array. In this case it is 1 as it is a 1D array.Gives the number of dimensions in the numpy array.
# So for a 2D array it will print 2 and so on.
anotherexample = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(anotherexample.ndim)

1
2


In [27]:
# Similarly we can create 2D,3D arrays using nested lists.
ThreeDarray = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12], 
        [13,14,15], 
        [16,17,18]
    ]
])

In [29]:
# Now we can do a different type of slicing in multi-dimensional arrays.
print(ThreeDarray[:,:,2:]) # What this means is that it will slice the first dimension and in that whatever is choosen it will slice the second dimension and in that whatever is choosen it will slice the third dimension from it.

[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]]


In [31]:
# Same goes with the indexing as well.
print(ThreeDarray[1,2,0]) # This will print 16. 1st Row in Dimension_1 and 2nd Row in Dimension_2 and 0th element in the 3rd Dimension(Last).
# This is pretty useful.

16


In [33]:
# A few methods to create numpy arrays quickly.
zerosarray = np.zeros((3,4)) # Creates a 3x4 array filled with zeros. The syntax is usually like this np.zeros((rows,columns))
onesarray = np.ones((2,3,4),dtype = np.int16) # Creates a 2x3x4 array filled with ones.
fullarray = np.full((2,2),7) # Creates a 2x2 array filled with the number 7.
randomarray = np.random.rand(3,4) # Creates a 3x4 array filled with random numbers between 0 and 1.
# There are many more methods to create numpy arrays quickly like arange(),linspace() etc.

In [38]:
# We can create 0 array, 1s array and full and empty as well. The empty one is extremely useful whenever we want to create an array with garbage valuer taking up minimal memory and really good speed as well.
# We can use the .eye method to create identity matrices as well.
identitymatrix = np.eye(10,dtype = np.int8) # Creates a 10x10 identity matrix.
print(identitymatrix) # The datatype can be changed as well.

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [39]:
# Scalar operations on numpy arrays.
scaledarray = example * 2 # This will multiply every element in the array by 2.
print(scaledarray)

[200.   4.   6.   8.  90.  10.  12.  14.  16.  18.   0.]


In [42]:
# Matrix multiplcations can be done using the following methods...
"""
1) Using the @ operator.
2) Using the np.dot() method.
The difference between the both is that the @ operator can be used for both 1D and 2D arrays whereas the np.dot() method is used for 2D arrays only.
"""
# So using the @ operator is better.
## The condition for matrix multiplication is that the number of columns in the first matrix should be equal to the number of rows in the second matrix.
## C1 = R2 resulting in C2 R1 matrix.
E1 = np.array([[1,2,3],[34,5,3]])
E2 = np.array([[1,2,3],[1,2,3],[4,5,6]])
print(E1 @ E2) # This will work.
# But the np.dot() operation will not work for 1D arrays. So i dont see the point of using it.

[[ 15  21  27]
 [ 51  93 135]]


In [43]:
# Few other methods as well.
## Transpose of a matrix.
print(E1.T) # This will print the transpose of the matrix E1.

[[ 1 34]
 [ 2  5]
 [ 3  3]]


In [50]:
# Arange and linsapce methods to create numpy arrays quickly.
arangearray = np.arange(1,10) # This means it will create an array starting from 1 to 10 leaving a gap of 2 in b/w.
print(arangearray)
# To get the number of elements present in that array we do the following.
print(arangearray.size) 

[1 2 3 4 5 6 7 8 9]
9


In [58]:
# Now linsapce.
linspacearray = np.linspace(1,10,5,endpoint=True) # This will create an array starting from 1 to 10 with 5 elements in total.
# Includes the endpoint as well.
print(linspacearray[:])

[ 1.    3.25  5.5   7.75 10.  ]


In [60]:
# Now to resize the array.
shape = (2,2) # This is the new shape we want.
try:
    if linspacearray.size > 1:
        linspacearray.resize(shape)
except Exception as e:
    print(f"Unexpected Error Occured: {e}.") # Handling that exception if that shape isnt correct.

Unexpected Error Occured: cannot resize this array: it does not own its data.


In [61]:
# Now revising whatever I had learnt earlier.

In [63]:
# We can even set the dimension for a numpy array.
a = np.array([1,2,3,4,5,6],dtype = np.int8,ndmin=2) # This will create a 2D array.Its much more convinient.

In [64]:
# We can check for the dtype as well.
a.dtype

dtype('int8')

In [66]:
# Indexing a bit in depth.
numpyarray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(numpyarray[1][2]) # This will print 8. 1st row and 2nd column.
print(numpyarray[1,2])

8
8


In [68]:
print(numpyarray[:,:2]) # This is applicable to indexing as well.
print(numpyarray[:2,:2])

[[ 1  2]
 [ 6  7]
 [11 12]]
[[1 2]
 [6 7]]


In [69]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1] = 100
print(b[1])

[100 100 100]


In [70]:
# Summary statistics methods in numpy.
simplearray = np.array([1,2,3,4,5,6,7,8,9,10])
print(simplearray.sum()) # Sum of all elements in the array.
print(simplearray.mean()) # Mean of all elements in the array.
print(simplearray.std()) # Standard Deviation of all elements in the array.
print(simplearray.var()) # Variance of all elements in the array.
print(simplearray.min()) # Minimum element in the array.
print(simplearray.max()) # Maximum element in the array.
print(simplearray.argmax()) # Index of the maximum element in the array.
print(simplearray.argmin()) # Index of the minimum element in the array.

55
5.5
2.8722813232690143
8.25
1
10
9
0


In [71]:
# Okay so this is the concept of axis in numpy arrays.
""" 
In numpy arrays, axis refers to the dimensions along which operations are performed.
Axis 0 refers to the rows (vertical direction) and Axis 1 refers to the columns (horizontal direction).
For example, in a 2D array:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
axis 0 would refer to the columns (1, 4, 7), (2, 5, 8), and (3, 6, 9), while axis 1 would refer to the rows (1, 2, 3), (4
Basically axis 0 means the first element of the rows and axis 1 means the first element of the columns.
"""

' \nIn numpy arrays, axis refers to the dimensions along which operations are performed.\nAxis 0 refers to the rows (vertical direction) and Axis 1 refers to the columns (horizontal direction).\nFor example, in a 2D array:\narray = np.array([[1, 2, 3],\n                  [4, 5, 6],\n                  [7, 8, 9]])\naxis 0 would refer to the columns (1, 4, 7), (2, 5, 8), and (3, 6, 9), while axis 1 would refer to the rows (1, 2, 3), (4\nBasically axis 0 means the first element of the rows and axis 1 means the first element of the columns.\n'

In [72]:
ThreeDarray = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ],
    [
        [10,11,12], 
        [13,14,15], 
        [16,17,18]
    ]
])

In [74]:
print(ThreeDarray.sum(axis = 2)) # This will sum all the elements along axis 2 i.e the 3rd dimension.)
# So each dimension can basically be thought of as a matrix itself. So summing along axis 2 means summing the elements in each matrix along the rows.

[[ 6 15 24]
 [33 42 51]]


In [75]:
# Vectorized operations in numpy and Broadcasting.
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(array1 + array2) # This will add the two arrays element wise.

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [76]:
# This is extremely useful this can be used for multiplication,subtraction and division as well.
print(array1 * array2)
print(array1 - array2)
print(array1 / array2)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [77]:
# In scalar operations on numpy arrays,each element of the array is broadcasted with the scalar value.
scaledarray = array1 * 10 # This will multiply each element of array1 by 10.
print(scaledarray)  

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [78]:
# The values are permanently changed in the array only when the assignment operator is used.

In [79]:
# Boolean Masking.
boolmask = array1 > 5 # This will create a boolean mask where each element greater than 5 will be True and the rest will be False.

In [81]:
# We can use logical operations for boolean masking as well for example...
logicalmask = (array1 > 2) & (array1 < 8) # This will create a boolean mask where each element greater than 2 and less than 8 will be True and the rest will be False.
print(logicalmask)

[[False False  True]
 [ True  True  True]
 [ True False False]]


In [86]:
# We can mask indirectly using the where operator, for example... 
print(np.where(array1 > 5,10,11)) # So where condition works like if the condition is True it will replace the value with the 'True' element else it will replace with the 'False' element.
# The syntax for it is as follows:
# np.where(<condition>,<True element>,<False element>)

[[11 11 11]
 [11 11 10]
 [10 10 10]]


In [87]:
# argmin and armax are used to get the index of the minimum and maximum element in the array respectively.

In [89]:
# Similar to where operation we have the extract method as well.
print(np.extract(array1 > 5,array1)) # This will extract all the elements greater than 5 from array1.
# Syntaxl- np.extract(<condition>,<array>)

[6 7 8 9]


In [93]:
A = np.random.randint(99,100,(2,2)) # The syntax is np.random.randint(<low>,<high>,(shape))
print(A)

[[99 99]
 [99 99]]


In [ ]:
# Linear Algebra in numpy.
## We know @ and np.dot() are used for matrix multiplication.
# Transpose is done using .T attribute.
## Then linalg module in numpy provides us with various methods for linear algebra operations.


In [97]:
# Some random module functions.
randomarray = np.random.rand(3,4) # This will create a 3x4 array with random values between 0 and 1.
print(randomarray)
randomarray = np.random.randn(3,4) # This will create a 3x4 array with random values from standard normal distribution.
print(randomarray)
randomarray = np.random.randint(1,100,(3,4)) # This will create a 3x4 array with random integers between 1 and 100.
print(randomarray)

[[0.27171487 0.76949664 0.25747012 0.58238531]
 [0.23214608 0.66910092 0.22302647 0.51786532]
 [0.77192703 0.6057635  0.88071836 0.94527534]]
[[ 0.4677962  -0.62380116  0.40931554  0.77116186]
 [-0.10738535  1.08214555 -0.20441006  0.24777471]
 [ 0.74978986 -2.93313413  0.48341697  0.2927726 ]]
[[ 9 91 26 27]
 [28 93 16 75]
 [19 50 53  5]]


In [99]:
flattened = ThreeDarray.flatten() # This will flatten the 3D array into a 1D array.
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [106]:
# To merge two arrays we use the concatenate method.
A = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
mergedarray = np.concatenate((A,b),axis=1) # This will merge the two arrays along axis 0 i.e rows.
print(mergedarray)
mergedarray = np.hstack((A,b)) # This will merge the two arrays along axis 1 i.e columns.
print(mergedarray)

# So the concatenate method with the axis parameter and hstack and vstack methods can be used to merge arrays. Both are literally the same.

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# Okay thats about it for numpy I will give even more depth if needed later on while doing the projects.